### ISSUE TITLE
test/document mermaid plugin

### ISSUE THREAD

**Issue by ntno** [ntno/mkdocs-terminal#153]
https://github.com/fralau/mkdocs-mermaid2-plugin
does it work?

**Comment by ntno** [comment]
tried the following but it didn't work.  i'm not super excited about digging into this so i am going to close this issue rather than let it sit around and get stale.

MkDocs Plugin Config:
```
plugins:
  - md-to-html
  - git-revision-date
  - mermaid2:
      version: 10.0.2
      arguments:
        theme: 'dark'
        themeVariables:
          primaryColor: '#BB2528'
          primaryTextColor: '#fff'
          primaryBorderColor: '#7C0000'
          lineColor: '#F8B229'
          secondaryColor: '#006100'
          tertiaryColor: '#fff'
```

MkDocs Extensions Config:

```yaml
markdown_extensions:
  # Python Markdown  
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference

  # PyMdown Extensions
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: 
        - docs
  - pymdownx.superfences

```
Requirements:
```
mkdocs-mermaid2-plugin>=1.0.8
```

Markdown:

````markdown
```mermaid
graph LR
    hello --> world
    world --> again
    again --> hello
```
````
