### ISSUE TITLE
can't run pytests on windows due to problem installing pytidylib

### ISSUE THREAD

**Issue by ntno** [ntno/mkdocs-terminal#59]
### Description

when pytests run on windows-latest github action runner i get the following error:

### Reproduction
install tidy with soop:
```
      - if: ${{ matrix.platform == 'windows-latest' }}
        name: Install scoop (Windows)
        uses: MinoruSekine/setup-scoop@main
        with: 
          scoop_update: false
      - if: ${{ matrix.platform == 'windows-latest' }}
        name: Install test requirements (windows)
        run: |
          scoop install tidy
```
> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

> Please provide the following:

- **Version of this theme used:**
- **Version of MkDocs used**
- **Other relevant versions (pip packages, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**
